# Generated by Django 4.2.2 on 2024-03-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='name',
            field=models.CharField(default=[""], max_length=255),
            preserve_default=False,
        ),
    ]
